server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://${127.0.0.1:localhost}:3306/test_db"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
